### ISSUE TITLE
Unicode error prevents opening the scratchpad

### ISSUE THREAD

**Issue by marcaube** [i-anunay/sublime_scratchpad#5]
My scratchpad won't open anymore. It seems like the plugin has a problem with a unicode character I typed in my scratchpad the last time I used it.

Here's the error I got in the SublimeText console

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "Scratchpad in /Users/marc/Library/Application Support/Sublime Text 3/Installed Packages/Scratchpad.sublime-package", line 29, in run
  File "Scratchpad in /Users/marc/Library/Application Support/Sublime Text 3/Installed Packages/Scratchpad.sublime-package", line 43, in putTimeStamp
  File "Scratchpad in /Users/marc/Library/Application Support/Sublime Text 3/Installed Packages/Scratchpad.sublime-package", line 43, in <genexpr>
  File "./python3.3/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1124: ordinal not in range(128)
```

**Comment by Dascr32** [comment]
@marcaube  I encountered the same issue today. I'll take a look at the code and submit a PR in the next couple of days. 

If you need to open the scratchpad file, follow this steps: 

1. Paste this in the sublime console:

```python
from sublime import packages_path
packages_path()[:-8]

# It should output something like /Users/username/Library/Application Support/Sublime Text 3/
```
2. Go to `Finder > Go > Go To Folder` and paste the path. The `scratchpad.txt` file should be there.

**Comment by marcaube** [comment]
@Dascr32 for now, I've added a `scratchpad` alias to my terminal. It opens the scratchpad file with Sublime's binary.

```bash
scratchpad='subl ~/Library/Application\ Support/Sublime\ Text\ 3/scratchpad.txt'
```
